# Basic
title: FellowPlus Dev
subtitle: 技术团队
welcome_message: <a href="https://fellowplus.com" target="_blank">FellowPlus.com</a>
description: 欢迎来到我们的秘密花园，期待一同分享更多技术干果.
creator: <a href="http://binboy.top">@Binboy</a>

url: "http://fellowplusdev.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: plain
# markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 欢迎进入

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.example.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: fellowplusdev
    # duoshuo: 
    
# Social
social:
    # weibo: onevcat
    github: fellowplusdev
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: hi@fellowplus.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
